version: "3.2"

services:
    usercityapp:
        image: php:7.1.11-fpm-alpine3.4
        volumes:
            - .:/source
        expose:
            - "9000"

    httpserver: #nginx docker container
        image: nginx:alpine
        volumes:
            - ./docker/nginx/conf:/etc/nginx/conf.d
            - ./docker/nginx/logs:/var/log/nginx
            - .:/source
        ports:
            - "33080:80"
        expose:
            - "80"
            - "443"

# networks:
